apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      labels:
        app: tomcatapp
    spec:
      containers:
      - image: tomcat:8.0
        name: tomcatapp
        ports:
        - containerPort: 8080
        
        
        
        